name = "VanillaToys 1.21.3"
author = "Fabi.exe"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a75fd199b1f1966756bbcec35f3b182735b84b066992ae76739696e2ff5bf48"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
