name = "VanillaToys+ 1.21.3"
author = "Fabi.exe"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3f5851c557c1e8ea7c8f78dbce47bee70ddf6839428cf9b69fbd8058b2f3989"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
